// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eigenMatMult
SEXP eigenMatMult(Eigen::MatrixXd A, Eigen::MatrixXd B);
RcppExport SEXP _SuperJump_eigenMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// eigenMapMatMult
SEXP eigenMapMatMult(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> B);
RcppExport SEXP _SuperJump_eigenMapMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMapMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// eigenMatInverse
SEXP eigenMatInverse(const Eigen::Map<Eigen::MatrixXd> A);
RcppExport SEXP _SuperJump_eigenMatInverse(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMatInverse(A));
    return rcpp_result_gen;
END_RCPP
}
// eigenMatXMatXMatINV
SEXP eigenMatXMatXMatINV(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> B, const Eigen::Map<Eigen::MatrixXd> C);
RcppExport SEXP _SuperJump_eigenMatXMatXMatINV(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMatXMatXMatINV(A, B, C));
    return rcpp_result_gen;
END_RCPP
}
// eigenOutputFlightTime
SEXP eigenOutputFlightTime(const Eigen::Map<Eigen::MatrixXd> Qmat, const Eigen::Map<Eigen::MatrixXd> Rmat);
RcppExport SEXP _SuperJump_eigenOutputFlightTime(SEXP QmatSEXP, SEXP RmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Qmat(QmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Rmat(RmatSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenOutputFlightTime(Qmat, Rmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SuperJump_eigenMatMult", (DL_FUNC) &_SuperJump_eigenMatMult, 2},
    {"_SuperJump_eigenMapMatMult", (DL_FUNC) &_SuperJump_eigenMapMatMult, 2},
    {"_SuperJump_eigenMatInverse", (DL_FUNC) &_SuperJump_eigenMatInverse, 1},
    {"_SuperJump_eigenMatXMatXMatINV", (DL_FUNC) &_SuperJump_eigenMatXMatXMatINV, 3},
    {"_SuperJump_eigenOutputFlightTime", (DL_FUNC) &_SuperJump_eigenOutputFlightTime, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SuperJump(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
