// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eigenMatMult
SEXP eigenMatMult(Eigen::MatrixXd A, Eigen::MatrixXd B);
RcppExport SEXP _SupeRJump_eigenMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// eigenMapMatMult
SEXP eigenMapMatMult(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> B);
RcppExport SEXP _SupeRJump_eigenMapMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMapMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}
// eigenMatInverse
SEXP eigenMatInverse(const Eigen::Map<Eigen::MatrixXd> A);
RcppExport SEXP _SupeRJump_eigenMatInverse(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMatInverse(A));
    return rcpp_result_gen;
END_RCPP
}
// eigenMatXMatXMatINV
SEXP eigenMatXMatXMatINV(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::MatrixXd> B, const Eigen::Map<Eigen::MatrixXd> C);
RcppExport SEXP _SupeRJump_eigenMatXMatXMatINV(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMatXMatXMatINV(A, B, C));
    return rcpp_result_gen;
END_RCPP
}
// eigenOutputFlightTime
SEXP eigenOutputFlightTime(const Eigen::Map<Eigen::MatrixXd> Qmat, const Eigen::Map<Eigen::MatrixXd> Rmat);
RcppExport SEXP _SupeRJump_eigenOutputFlightTime(SEXP QmatSEXP, SEXP RmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Qmat(QmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Rmat(RmatSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenOutputFlightTime(Qmat, Rmat));
    return rcpp_result_gen;
END_RCPP
}
// flighttime_sparse_targets_cpp
Rcpp::NumericMatrix flighttime_sparse_targets_cpp(const Eigen::MappedSparseMatrix<double>& P, Rcpp::IntegerVector targets, bool targets_in_rows, double hit_tol, int n_threads);
RcppExport SEXP _SupeRJump_flighttime_sparse_targets_cpp(SEXP PSEXP, SEXP targetsSEXP, SEXP targets_in_rowsSEXP, SEXP hit_tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type P(PSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< bool >::type targets_in_rows(targets_in_rowsSEXP);
    Rcpp::traits::input_parameter< double >::type hit_tol(hit_tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(flighttime_sparse_targets_cpp(P, targets, targets_in_rows, hit_tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cmfpt_sparse_targets_cpp
Rcpp::NumericMatrix cmfpt_sparse_targets_cpp(const Eigen::MappedSparseMatrix<double>& P, Rcpp::IntegerVector targets, bool targets_in_rows, double hit_tol, int interrupt_every);
RcppExport SEXP _SupeRJump_cmfpt_sparse_targets_cpp(SEXP PSEXP, SEXP targetsSEXP, SEXP targets_in_rowsSEXP, SEXP hit_tolSEXP, SEXP interrupt_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type P(PSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< bool >::type targets_in_rows(targets_in_rowsSEXP);
    Rcpp::traits::input_parameter< double >::type hit_tol(hit_tolSEXP);
    Rcpp::traits::input_parameter< int >::type interrupt_every(interrupt_everySEXP);
    rcpp_result_gen = Rcpp::wrap(cmfpt_sparse_targets_cpp(P, targets, targets_in_rows, hit_tol, interrupt_every));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SupeRJump_eigenMatMult", (DL_FUNC) &_SupeRJump_eigenMatMult, 2},
    {"_SupeRJump_eigenMapMatMult", (DL_FUNC) &_SupeRJump_eigenMapMatMult, 2},
    {"_SupeRJump_eigenMatInverse", (DL_FUNC) &_SupeRJump_eigenMatInverse, 1},
    {"_SupeRJump_eigenMatXMatXMatINV", (DL_FUNC) &_SupeRJump_eigenMatXMatXMatINV, 3},
    {"_SupeRJump_eigenOutputFlightTime", (DL_FUNC) &_SupeRJump_eigenOutputFlightTime, 2},
    {"_SupeRJump_flighttime_sparse_targets_cpp", (DL_FUNC) &_SupeRJump_flighttime_sparse_targets_cpp, 5},
    {"_SupeRJump_cmfpt_sparse_targets_cpp", (DL_FUNC) &_SupeRJump_cmfpt_sparse_targets_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SupeRJump(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
