# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Eigen Matrix Multiplication
#'
#' An alternative to \code{format.POSIXct} based on the CCTZ library. The
#' \code{formatDouble} variant uses two vectors for seconds since the epoch
#' and fractional nanoseconds, respectively, to provide fuller resolution.
#'
#' @title Format a Datetime vector as a string vector
#' @param dtv A Datetime vector object to be formatted
#' @param fmt A string with the format, which is based on \code{strftime} with some
#'   extensions; see the CCTZ documentation for details.
#' @param lcltzstr The local timezone object for creation the CCTZ timepoint
#' @param tgttzstr The target timezone for the desired format
#' @return A string vector with the requested format of the datetime objects
#' @section Note:
#' Windows is now supported via the \code{g++-4.9} compiler, but note
#' that it provides an \emph{incomplete} C++11 library. This means we had
#' to port a time parsing routine, and that string formatting is more
#' limited. As one example, CCTZ frequently uses \code{"\%F \%T"} which do
#' not work on Windows; one has to use \code{"\%Y-\%m-\%d \%H:\%M:\%S"}.
#' @author Dirk Eddelbuettel
#' @examples
#' \dontrun{
#' now <- Sys.time()
#' formatDatetime(now)            # current (UTC) time, in full precision RFC3339
#' formatDatetime(now, tgttzstr="America/New_York")  # same but in NY
#' formatDatetime(now + 0:4)    # vectorised
#' }
eigenMatMult <- function(A, B) {
    .Call(`_SupeRJump_eigenMatMult`, A, B)
}

#' Eigen Matrix Multiplication Faster
#'
#' An alternative to \code{format.POSIXct} based on the CCTZ library. The
#' \code{formatDouble} variant uses two vectors for seconds since the epoch
#' and fractional nanoseconds, respectively, to provide fuller resolution.
#'
#' @title Format a Datetime vector as a string vector
#' @param dtv A Datetime vector object to be formatted
#' @param fmt A string with the format, which is based on \code{strftime} with some
#'   extensions; see the CCTZ documentation for details.
#' @param lcltzstr The local timezone object for creation the CCTZ timepoint
#' @param tgttzstr The target timezone for the desired format
#' @return A string vector with the requested format of the datetime objects
#' @section Note:
#' Windows is now supported via the \code{g++-4.9} compiler, but note
#' that it provides an \emph{incomplete} C++11 library. This means we had
#' to port a time parsing routine, and that string formatting is more
#' limited. As one example, CCTZ frequently uses \code{"\%F \%T"} which do
#' not work on Windows; one has to use \code{"\%Y-\%m-\%d \%H:\%M:\%S"}.
#' @author Michael Bowman
#' @examples
#' \dontrun{
#' now <- Sys.time()
#' formatDatetime(now)            # current (UTC) time, in full precision RFC3339
#' formatDatetime(now, tgttzstr="America/New_York")  # same but in NY
#' formatDatetime(now + 0:4)    # vectorised
#' }
eigenMapMatMult <- function(A, B) {
    .Call(`_SupeRJump_eigenMapMatMult`, A, B)
}

#' Eigen Matrix Inverse
#'
#' An alternative to \code{format.POSIXct} based on the CCTZ library. The
#' \code{formatDouble} variant uses two vectors for seconds since the epoch
#' and fractional nanoseconds, respectively, to provide fuller resolution.
#'
#' @title Format a Datetime vector as a string vector
#' @param dtv A Datetime vector object to be formatted
#' @param fmt A string with the format, which is based on \code{strftime} with some
#'   extensions; see the CCTZ documentation for details.
#' @param lcltzstr The local timezone object for creation the CCTZ timepoint
#' @param tgttzstr The target timezone for the desired format
#' @return A string vector with the requested format of the datetime objects
#' @section Note:
#' Windows is now supported via the \code{g++-4.9} compiler, but note
#' that it provides an \emph{incomplete} C++11 library. This means we had
#' to port a time parsing routine, and that string formatting is more
#' limited. As one example, CCTZ frequently uses \code{"\%F \%T"} which do
#' not work on Windows; one has to use \code{"\%Y-\%m-\%d \%H:\%M:\%S"}.
#' @author Michael Bowman
#' @examples
#' \dontrun{
#' now <- Sys.time()
#' formatDatetime(now)            # current (UTC) time, in full precision RFC3339
#' formatDatetime(now, tgttzstr="America/New_York")  # same but in NY
#' formatDatetime(now + 0:4)    # vectorised
#' }
eigenMatInverse <- function(A) {
    .Call(`_SupeRJump_eigenMatInverse`, A)
}

#' Eigen Matrix Inverse and Double Multiply
#'
#' An alternative to \code{format.POSIXct} based on the CCTZ library. The
#' \code{formatDouble} variant uses two vectors for seconds since the epoch
#' and fractional nanoseconds, respectively, to provide fuller resolution.
#'
#' @title Format a Datetime vector as a string vector
#' @param dtv A Datetime vector object to be formatted
#' @param fmt A string with the format, which is based on \code{strftime} with some
#'   extensions; see the CCTZ documentation for details.
#' @param lcltzstr The local timezone object for creation the CCTZ timepoint
#' @param tgttzstr The target timezone for the desired format
#' @return A string vector with the requested format of the datetime objects
#' @section Note:
#' Windows is now supported via the \code{g++-4.9} compiler, but note
#' that it provides an \emph{incomplete} C++11 library. This means we had
#' to port a time parsing routine, and that string formatting is more
#' limited. As one example, CCTZ frequently uses \code{"\%F \%T"} which do
#' not work on Windows; one has to use \code{"\%Y-\%m-\%d \%H:\%M:\%S"}.
#' @author Michael Bowman
#' @examples
#' \dontrun{
#' now <- Sys.time()
#' formatDatetime(now)            # current (UTC) time, in full precision RFC3339
#' formatDatetime(now, tgttzstr="America/New_York")  # same but in NY
#' formatDatetime(now + 0:4)    # vectorised
#' }
eigenMatXMatXMatINV <- function(A, B, C) {
    .Call(`_SupeRJump_eigenMatXMatXMatINV`, A, B, C)
}

#' Eigen for OutputFlightTime
#'
#' An alternative to \code{format.POSIXct} based on the CCTZ library. The
#' \code{formatDouble} variant uses two vectors for seconds since the epoch
#' and fractional nanoseconds, respectively, to provide fuller resolution.
#'
#' @title Format a Datetime vector as a string vector
#' @param dtv A Datetime vector object to be formatted
#' @param fmt A string with the format, which is based on \code{strftime} with some
#'   extensions; see the CCTZ documentation for details.
#' @param lcltzstr The local timezone object for creation the CCTZ timepoint
#' @param tgttzstr The target timezone for the desired format
#' @return A string vector with the requested format of the datetime objects
#' @section Note:
#' Windows is now supported via the \code{g++-4.9} compiler, but note
#' that it provides an \emph{incomplete} C++11 library. This means we had
#' to port a time parsing routine, and that string formatting is more
#' limited. As one example, CCTZ frequently uses \code{"\%F \%T"} which do
#' not work on Windows; one has to use \code{"\%Y-\%m-\%d \%H:\%M:\%S"}.
#' @author Michael Bowman
#' @examples
#' \dontrun{
#' now <- Sys.time()
#' formatDatetime(now)            # current (UTC) time, in full precision RFC3339
#' formatDatetime(now, tgttzstr="America/New_York")  # same but in NY
#' formatDatetime(now + 0:4)    # vectorised
#' }
eigenOutputFlightTime <- function(Qmat, Rmat) {
    .Call(`_SupeRJump_eigenOutputFlightTime`, Qmat, Rmat)
}

flighttime_sparse_targets_cpp <- function(P, targets, targets_in_rows = TRUE, hit_tol = 1e-14, n_threads = 1L) {
    .Call(`_SupeRJump_flighttime_sparse_targets_cpp`, P, targets, targets_in_rows, hit_tol, n_threads)
}

cmfpt_sparse_targets_cpp <- function(P, targets, targets_in_rows = FALSE, hit_tol = 1e-14, interrupt_every = 32L) {
    .Call(`_SupeRJump_cmfpt_sparse_targets_cpp`, P, targets, targets_in_rows, hit_tol, interrupt_every)
}

